import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0B0B0F",
        foreground: "#F5F5F5",
        surface: "#15151C",
        card: "#1D1D26",
        "surface-dim": "#1e100e",
        "surface-bright": "#473532",
        "surface-container-lowest": "#180a09",
        "surface-container-low": "#271816",
        "surface-container": "#2c1c1a",
        "surface-container-high": "#372624",
        "surface-container-highest": "#43302e",
        "on-surface": "#f9dcd8",
        "on-surface-variant": "#e4beb9",
        "inverse-surface": "#f9dcd8",
        "inverse-on-surface": "#3e2c2a",
        outline: "#ab8985",
        "outline-variant": "#5b403d",
        "surface-tint": "#ffb4ab",
        primary: "#ffb4ab",
        "on-primary": "#690005",
        "primary-container": "#b91c1c",
        "on-primary-container": "#ffcdc7",
        "inverse-primary": "#b91c1c",
        secondary: "#c8c5cf",
        "on-secondary": "#303037",
        "secondary-container": "#494850",
        "on-secondary-container": "#b9b7c1",
        tertiary: "#a0caff",
        "on-tertiary": "#003259",
        "tertiary-container": "#0061a6",
        "on-tertiary-container": "#c1dbff",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        accent: "#B91C1C",
        danger: "#B91C1C",
        success: "#22c55e",
        warning: "#f59e0b",
        border: "rgba(255, 255, 255, 0.1)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        label: ["var(--font-label)"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      spacing: {
        "edge-mobile": "20px",
        gutter: "32px",
        "section-gap": "120px",
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
export default config;
